### ISSUE TITLE
Territory points considered as neutral

### ISSUE THREAD

**Issue by arnaudgo** [online-go/score-estimator#1]
In one game [1], ogs score estimator made 11 points of Black territory neutral points.

![territory_as_dame](https://cloud.githubusercontent.com/assets/26174230/24166228/8098ed9c-0e6a-11e7-96cc-17f417d98b08.jpg)

Could you please confirm there's a bug and fix it when you have time.

1: https://online-go.com/game/8075913

**Comment by anoek** [comment]
Seems to perform better with the recent changes
