### ISSUE TITLE
question about function Goban::is_eye()

### ISSUE THREAD

**Issue by wjx0912** [online-go/score-estimator#12]
in function:  bool Goban::is_eye(Point pt, Color player) const 

the original code:
`
        if (board.countEqual(corners, -player) >= (corners.size >> 1) && board.getMinLibertiesOfSurroundingGroups(pt) <= 1) {
`
i think it should be
`
        if (board.countEqual(corners, -player) >= (corners.size >> 1) 
 || board.getMinLibertiesOfSurroundingGroups(pt) <= 1) {
`

any condition may cause false eye, so it should be ||, not &&?

**Comment by anoek** [comment]
Doing so causes a lot of tests to fail, so my immediate hunch is "nope"

**Comment by wjx0912** [comment]
thank you
