### ISSUE TITLE
use fast neural ("policy") network

### ISSUE THREAD

**Issue by siimphh** [online-go/score-estimator#3]
To make the score estimator more accurate, would it be plausible to consider training a fast and small policy network based on online-go game database to suggest "plausible" moves rather than completely random ones. The idea would not to select the "best" moves but just some indication of moves that may get played in practice.

A sufficiently small network may be able to concentrate the search space without too terrible computational overhead - potentially also dampened as the number of playouts could be reduced.

I'm basically mostly asking if there are reasons why this idea would be a non-starter or if it could be worth pursuing.

**Comment by anoek** [comment]
Yep I think this would help out tremendously.

**Comment by siimphh** [comment]
With https://github.com/gcp/leela-zero codebase it might be relatively easier to teach a shallow network some go. At the very least it is a reasonable example to follow.

Since the scoring (IIUIC) runs on the user's browser, presumably there are strict requirements for binady size and runtime memory/cpu usage for the scorer? Are there particular targets you were trying to hit (the readme just says "small" and "fast").

**Comment by lemonsqueeze** [comment]
I really like the idea too. Looks like the best solution, and with all the server data available, a perfect fit for network training. 

Better than policy network would be a value network that outputs board stones status. Then even without gpu performance would be really good, even faster than mc evaluations. And for scoring final positions i wouldn't be surprised a network can come close to 100% accuracy. I guess we need one network for each board size though... I'm pretty sure there are existing value networks we could try, i'll check opensource engines.

Does ogs server have a gpu ? If we want to use a network in the client-side score estimator as well, maybe javascript can just ask the server to do it and return the result...

**Comment by thouis** [comment]
There might be one here you could use: https://github.com/Rochester-NRT/RocAlphaGo

**Comment by lemonsqueeze** [comment]
Here we go: [jmgilmer/GoCNN](https://github.com/jmgilmer/GoCNN) - Using CNN for board evaluation for the game Go.
Also see this [thread](http://computer-go.org/pipermail/computer-go/2016-January/008414.html) on computer-go.org.

> For most games the model achieves > 96% accuracy at the end of the game. Note that accuracy is measured the average over all 361 spaces, which include neutral spaces that may exist between two live groups, these spaces were randomly assigned when gnugo finished the games and so it would be unreasonable to expect 100% accuracy even at the last move.

**Comment by siimphh** [comment]
Also of note is that tensorflow.js is now a thing. So getting the trained modem to run in the browser may be straightforward.

**Comment by lemonsqueeze** [comment]
<img align="right" src="https://user-images.githubusercontent.com/2463904/38249594-7bf67636-374c-11e8-8792-bf515fb26afa.png">

I tried GoCNN, looks like it's not going to help, too many life and death issues.  For example [this game](http://online-go.com/game/622861):

Depending on which rotation you use it finds the 2 big dead black groups dead or alive, same for seki in lower right (this one is pretty exotic, half of it is alive !)

But then it's a small network, bigger one would probably do better.

**Comment by anoek** [comment]
Closing as i think this is actually not going to be practical, the size of the nn's are rather large typically

**Comment by siimphh** [comment]
What kind of size limits do you have? I've trained my bot to do score estimation among other things and the  model weights are tens of megabytes. But I've not tried to train a network for that score estimation alone, it is possible it could be made a few orders of magnitude smaller on that case. Would hundreds of kilobytes be acceptable size or is that still too big?

Alternatively, the score-estimator could be run server-side. My laptop can evaluate these networks ~100x per second on CPU only, so it would not be infeasible to move the estimation from browser to server.

**Comment by anoek** [comment]
If we could get it under 1MB that would be great, but honestly if we had something that was even 5MB that was notably better than what we have, that would probably still be fine.

I'd be open to exploring a server side implementation as well, I resisted it for awhile because we don't exactly have a big budget for server side processing, but I am looking at expanding what we have so it might be a possibility soon.
