### ISSUE TITLE
fetch_ogs_game errors

### ISSUE THREAD

**Issue by roy7** [online-go/score-estimator#4]
The SSL connection fails as such:

requests.packages.urllib3.exceptions.SSLError: hostname 'ggs.online-go.com' doesn't match either of '*.idviu.io', 'idviu.io'

I tried fetching with http but no luck there either. http://ggs.online-go.com/napi/game-state/8605720/ just shows READY with no actual game info.

**Comment by yangboz** [comment]
They changed API to "'https://online-go.com/api/v1/games/%d/' % game_id",
Actually, any documentation on this change logs?

**Comment by anoek** [comment]
All fixed up
